language: python
python:
  - "3.6"
  - "3.7-dev"
  - "nightly"
  - "pypy3"
services:
  - mongodb
  - redis-server
env:
  - APP_NAME=travis-ci
before_install:
  - pip install pipenv
install:
  - pipenv install --dev
script:
  - pipenv run pytest
