language: python
python:
  - "3.6"
  - "3.7-dev"
  - "nightly"
  - "pypy3"
env:
  - APP_NAME=Travis
before_install:
  - pip install pipenv
install:
  - pipenv install --dev
script:
  - pipenv run pytest
